id: I4DD414F8
ocr_import_info:
  timestamp: '2023-09-28T02:50:19.433594+00:00'
  batch_id: batch-4600
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 04:30:46.666917+00:00
last_modified: 2023-09-28 04:30:46.666925+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74192
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74192
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་མཆན་འགྲེལ།
  languages:
  - bo
  author: རྒྱ་ཀོང་མཁན་ཆེན་གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9587606986453686
  ocr_word_median_confidence_index: 0.99466298
bases:
  I4CZ74255:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74255
      total_pages: 254
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74255.txt
    statistics:
      ocr_word_median_confidence_index: 0.99466298
      ocr_word_mean_confidence_index: 0.9587606986453686
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
